package com.srm.machinemonitor;

public class Constants {
    public static String MACHINE_NAME = "machineName";
    public static String SENSORS = "sensors";
    public static String SENSOR_NAME = "sensorName";
    public static String ORGANIZATION_ID = "organizationId";
    public static String SESSION = "session";
    public static String USERNAME = "username";
    public static String DATA = "data";
    public static String LASTSENTVALUE = "lastSentValue";
    public static String TO = "to";
    public static String HEARTBEAT = "heartbeat";
    public static String MISSBEAT = "missbeat";
    public static String LOGSUBSCRIBED = "logSubscribed";
    public static String MACHINENAME = "machineName";
    public static String DATASUBSCRIBED = "dataSubscribed";
    public static String SENSOR = "sensor";
    public static String ROLE = "role";
    public static String MACHINEID = "machineId";
    public static String STARTDATE = "startDate";
    public static String ENDDATE = "endDate";
    public static String ISALIVE = "isAlive";
    public static String ISHANDLED = "isHandled";
    public static String LASTDATATIME = "lastDataTime";
    public static String DEV = "dev";
    public static String PROD = "prod";
    public static String ADMIN = "admin";
    public static String MODE = "mode";
    public static String STATUS = "STATUS";
    public static String COMPLETED = "COMPLETED";
    public static String MACHINETOKEN = "MACHINE_TOEKN";
    public static String DATATYPE_PAYLOAD = "dataType";
    public static String ORGANIZATION_NAME = "organization";
    public static String IsArduinoCommand = "isArduinoCommand";
    public static String COMMAND = "command";
    public static String TYPE = "type";
    public static String LOGTYPE = "logType";
    public static String LOGDATA = "logData";
}
